### ISSUE TITLE
Problem with RegisterExtension

### ISSUE THREAD

**Issue by arolfes** [camunda-community-hub/camunda-bpm-process-test-coverage#122] opened 2021-10-29 15:06 UTC
When I use `@RegisterExtension` I can have only one testmethod per class

In the example below the second testmethod fails always with

### exception
```
kotlin.UninitializedPropertyAccessException: lateinit property activeSuite has not been initialized

	at org.camunda.bpm.extension.process_test_coverage.model.DefaultCollector.getActiveSuite(DefaultCollector.kt:17)
	at org.camunda.bpm.extension.process_test_coverage.junit5.ProcessEngineCoverageExtension.beforeTestExecution(ProcessEngineCoverageExtension.kt:89)
```

### Testcase
```kotlin
package org.camunda.bpm.extension.process_test_coverage.examples

import org.camunda.bpm.engine.ProcessEngineConfiguration
import org.camunda.bpm.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration
import org.camunda.bpm.engine.runtime.ProcessInstance
import org.camunda.bpm.engine.test.Deployment
import org.camunda.bpm.engine.test.assertions.bpmn.BpmnAwareTests.assertThat
import org.camunda.bpm.engine.test.assertions.bpmn.BpmnAwareTests.complete
import org.camunda.bpm.engine.test.assertions.bpmn.BpmnAwareTests.runtimeService
import org.camunda.bpm.engine.test.assertions.bpmn.BpmnAwareTests.task
import org.camunda.bpm.engine.test.assertions.bpmn.BpmnAwareTests.withVariables
import org.camunda.bpm.extension.process_test_coverage.junit5.ProcessEngineCoverageExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.junit.jupiter.api.extension.RegisterExtension

@Deployment(resources = ["order-process.bpmn"])
internal class OrderProcessKotlinTest {

    @JvmField
    @RegisterExtension
    val extension = ProcessEngineCoverageExtension.builder().build()


    @Test
    fun shouldExecuteHappyPath() {
        val instance = startProcess()
        assertThat(instance).isWaitingAt("Task_ProcessOrder")
        complete(
            task(),
            withVariables("orderOk", true)
        )
        assertThat(instance).isWaitingAt("Task_DeliverOrder")
        complete(task())
        assertThat(instance)
            .hasPassed("Event_OrderProcessed")
            .isEnded
    }

    @Test
    fun shouldCancelOrder() {
        val instance = startProcess()
        assertThat(instance).isWaitingAt("Task_ProcessOrder")
        complete(
            task(),
            withVariables("orderOk", false)
        )
        assertThat(instance)
            .hasPassed("Event_OrderCancelled")
            .isEnded
    }


    private fun startProcess(): ProcessInstance {
        return runtimeService().startProcessInstanceByKey("order-process")
    }

}
```

**Comment by rohwerj** [comment] 2021-10-29 19:38
Will provide a fix for this bug.
Actually the better way to register the extension is, to do it on a static field.
Otherwise the class coverage will not be triggered and no coverage report generated.
In the PR for the bugfix I will add this information in the documentation.

**Comment by zambrovski** [comment] 2021-10-30 12:27
@rohwerj thank you for the patch, I merged your PR in and the SNAPSHOT is now available in Sonatype OSS...

@arolfes could you please verify if the problem is also solved for your scenario?

**Comment by arolfes** [comment] 2021-10-30 12:36
Hi, thank you for the Patch, i will have a look on it on monday

**Comment by arolfes** [comment] 2021-11-02 07:55
The changes are working fine. Thank you

**Closed** 2021-11-02 08:42 UTC
Labels: Type: bug, Prio: MUST, Status: In progress
